{
    'name': 'Distribución - Base (delegaciones y roles)',
    'summary': 'Grupos de seguridad, delegaciones (almacenes), razones sociales e instituciones',
    'version': '19.0.1.0.0',
    'category': 'Distribución de insumos',
    'author': 'Alphaqueb Consulting SAS',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'stock', 'purchase'],
    'data': [
        'security/biotex_security.xml',
        'security/ir.model.access.csv',
        'data/company_data.xml',
        'views/stock_warehouse_views.xml',
        'views/res_users_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/menu_views.xml',
    ],
    'application': True,
    'installable': True,
}
